# Numpy : list with same datatype elements 

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array((1, 6, 3, 4, 9))
print(a)
print(b)

[1 2 3 4 5]
[1 6 3 4 9]


In [2]:
type(a)

numpy.ndarray

In [17]:
type(b)

numpy.ndarray

In [3]:
a.dtype

dtype('int32')

In [4]:
b.dtype

dtype('int32')

In [5]:
a = np.array([[1,2,3], 
              [4,5,6]])
a.ndim

2

In [18]:
a.shape

(2, 3)

In [6]:
a[0,2]

3

## properties of numpy

In [7]:
C = np.array([[[1,2,3], [4,5,6], [0, 0,-1]], [[-1, -2,-3], [-4,-5, -6], [0,0,1]]])
C.shape

(2, 3, 3)

here c[0] represent the number of 2-d array in the whole array 
     c[1] represent the number of 1-d array in each 2-d array 
     c[2] represent the number of elements or 0-d arrray in the each 1-d array

### Numpy(np.arange,reshape, random)

In [8]:
A = np.arange (20,100,3) # creates an array with following arrangements
print (A)

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


In [9]:
A = np.random.permutation (np.arange(10))
print (A)

[2 9 6 4 3 7 0 8 5 1]


In [10]:
 np.random.randint(1,10)

7

In [11]:
 np.random.randint(1,10,4)

array([8, 4, 1, 5])

In [12]:
 np.random.rand(3,2) # creates an array of given dimension here it is of 3*2 and all elements are between 0 an 1.

array([[0.91689507, 0.30424176],
       [0.08988547, 0.75311648],
       [0.21608901, 0.22166964]])

In [13]:
 np.random.randn(5,2) # same as rand but with a gaussian distribution.

array([[ 0.51615967, -0.48027342],
       [-0.20864566, -0.02322794],
       [ 1.28982594,  0.91788502],
       [ 0.23474   ,  0.5595665 ],
       [-2.77337422, -0.8966572 ]])

In [19]:
D = np.arange (100).reshape (4,25)
D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [15]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones(3,int)

array([1, 1, 1])